# Build output
base_html = "./src/base.html"
output_dir = "dist"

# Directories
[dirs]
root = "./src"
pages = "./src/pages"
posts = "./src/posts"
assets = "./src/assets"
styles = "./src/styles"
scripts = "./src/scripts"
components = "./src/components"

# Draft handling
draft_prefix = "_"